version: '3.8'
services:

  windows:
    working_dir: /app
    container_name: mfm-windows
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile.windows
    volumes:
    - ./output/windows:/app/dist_electron

  linux:
    container_name: mfm-linux
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile.ubuntu
    volumes:
    - ./output/ubuntu:/app/dist_electron
  
  macos:
    working_dir: /app
    container_name: mfm-macos
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile.macos
    volumes:
    - ./output/macos:/app/dist_electron