version: '3.8'
services:

  ubuntu:
    container_name: mfm
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    volumes:
    - ./output/ubuntu:/app/dist_electron
  
  macos:
    working_dir: /app
    container_name: mfm
    build:
      context: .
      dockerfile: Dockerfile.macos
    volumes:
    - ./output/macos:/app/dist_electron