FROM sickcodes/docker-osx:catalina

WORKDIR /app

COPY /app /app

#download homebrew installer
RUN curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh -o - > install.sh
#install homebrew
RUN /bin/bash install.sh

CMD npm run electron:build -- --macos dmg