name: Build for Ubuntu and macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: dev

jobs:
  build:
    # Run builds on two operating systems: ubuntu-latest and macos-latest
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Use consistent Node.js versions
        node-version: [22.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build -- --publish never
